### ISSUE TITLE
Possible memory / file descriptor leak

### ISSUE THREAD

**Issue by oubiwann** [USGS-EROS/lcmap-data#1]
Probably more than possible, really -- in REPL tests, I've managed to run out of FDs ...

Here are the details:

It looks like there's a memory leak in the lcmap-data-clj code when ingesting. The datasets are not getting deleted after creation. In particular, if you look at this line:
- https://github.com/USGS-EROS/lcmap-data-clj/blob/master/src/lcmap_data_clj/ingest.clj#L24

you'll see that `gdal.core/open` is called on the file, and the resultant dataset is returned from this function as part of a data structure. The resultant data is a GDAL object which has a `delete` method -- a method that never gets called in the code.

This results in two potential problems (one, for sure):
1. since the data is from a C or C++ function, I don't believe the JVM manages all of the related the memory, so when the context in which the `open` call is made is finished, some bits may still laying around.
2. since that function actually opens a file, once the context closes, there is an orphaned FD

I'm not sure, but the JVM may actually be smart enough to identify any orphaned objects and garbage collect them --  the tests I did on this were inconclusive, but enough so that one may be able to draw that conclusion. I leave that up to @davidvhill , who I believe has more experience here than the rest of us.

I was, however, able to very quickly get a NPE as a result of the orphaned FDs.

To fix this, we'll need to call `(.delete data-set)` on every object returned from `gdal.core/open`. (Once clj-gdal supports a `dataset/delete` function, we can stop using the interop call.) I'd recommend doing all of this in the same context as the `open` call is made, otherwise we'll lose track of the objects (eventually). This may require pulling out only what's needed (e.g. band data) and then deleting the dataset object.

**Comment by ghost** [comment]
Not that my comment is apples to apples with clojure or jvm, but in python....
I have always been explicitly deleting gdal objects.  I think it was when I finally was looking at the memory usage of my script, and noticed things were not getting freed when I expected them to.  So I reverted to always deleting the gdal object when I no longer need it.

**Comment by oubiwann** [comment]
Yeah, I think you're right and something very similar may have to be done here ... I was telling Jon that I didn't think just this one find was going to explain all of the memory issues with his JVMs ...

**Comment by jmorton** [comment]
This has been fixed by the recent overhaul, relying in part on a feature added to clj-gdal. I suggest we close this issue.

We now implicitly open and close a dataset in the context in which it is needed using a `with-dataset` macro, so we side-step some of the cognitive load needed to keep track of an open a dataset and figuring out when it is safe to close. However, still need to keep an eye out for potential problems with this approach. There are lower level dataset open/close functions defined in clj-gdal we can use instead.

One of the major differences between the original ingest code and the new approach is a complete departure from a feature that involved opening an in-memory dataset used to hold a reframed (not resampled) raster. I think this was the problem. In looking at the previous version I noticed that the in-memory dataset was never explicitly closed.
