### ISSUE TITLE
Reducers version of ingest code seems to block

### ISSUE THREAD

**Issue by oubiwann** [USGS-EROS/lcmap-data#6]
Processing does not actually seem to be happening in parallel for the reducers branch. This could be for one of the following reasons:
- reification of sequences is behaving differently than expected
- calls out to GDAL are blocking the application

Could also be both or neither ;-) Need to dive into this.

Note that the same problem was noticed on an unpublished branch using tesser. Once this is fixed, we can give tesser another chance ...

**Comment by jmorton** [comment]
The current branch uses pmap in order to concurrently ingest multiple bands. The debug log output indicates that this isn't a problem (tiles from multiple bands are interleaved). I suggest closing this issue unless you think it makes sense to pursue the reducers approach or see some sort of blocking in the dataflow with the most recent version.
